plugins:
  - rubocop-rails
AllCops:
  NewCops: enable

Style/Documentation:
  Enabled: false

Metrics/BlockLength:
  Exclude:
    - 'config/environments/**'
    - 'spec/models/**'
    - 'spec/services/**'

Rails/StrongParametersExpect:
  Exclude:
    - 'app/controllers/**'

Style/FetchEnvVar:
  Exclude:
    - 'config/environments/**'