plugins:
  - rubocop-rails
  - rubocop-rspec
  - rubocop-factory_bot
  - rubocop-haml
AllCops:
  NewCops: enable

Style/Documentation:
  Enabled: false

Metrics/BlockLength:
  Exclude:
    - 'config/environments/**'
    - 'spec/models/**'
    - 'spec/services/**'

Rails/StrongParametersExpect:
  Exclude:
    - 'app/controllers/**'

Style/FetchEnvVar:
  Exclude:
    - 'config/environments/**'

Rails/SkipsModelValidations:
  Exclude:
    - 'app/controllers/**'

RSpec/NestedGroups:
  Exclude:
    - 'spec/requests/**'

RSpec/LetSetup:
  Exclude:
    - 'spec/requests/**'
