service: rails_library

image: your-user/rails_library

servers:
  web:
    - 192.168.0.1

proxy:
  ssl: true
  host: app.example.com

registry:

  username: your-user

  password:
    - KAMAL_REGISTRY_PASSWORD

env:
  secret:
    - RAILS_MASTER_KEY

aliases:
  console: app exec --interactive --reuse "bin/rails console"
  shell: app exec --interactive --reuse "bash"
  logs: app logs -f
  dbc: app exec --interactive --reuse "bin/rails dbconsole"

asset_path: /rails/public/assets

builder:
  arch: amd64
