development:
  clients:
    default:
      uri: <%= ENV['MONGO_DB_CONNECT'] %>
      options:
        server_selection_timeout: 5
test:
  clients:
    default:
      database: rails_library_test
      hosts:
        - localhost:27017
      options:
        read:
          mode: :primary
        max_pool_size: 1
