development:
  clients:
    default:
      uri: <%= ENV['MONGO_DB_CONNECT'] %>
      options:
        server_selection_timeout: 5
test:
  clients:
    default:
      uri: <%= ENV['MONGO_DB_CONNECT_TEST'] %>
      options:
        server_selection_timeout: 5
